---
title: "Typha"
author: "Jenny Rogers"
date: "May 6, 2020"
output: html_document
---

```{r}
library(tidyverse)


```



Plots and model for velocity
```{r}
load("typha_velocity.RData")  


ggplot(data = velocity, mapping = aes(x = vel_m_s, y = occurrence))+
  geom_point(alpha = 0.2, size = 3)+
  labs(x = "Velocity (m/s)", y = "Occurrence")+
  geom_smooth(method = "glm", method.args = list(family = "binomial"))+
  theme(text = element_text(size=20), panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
        panel.background = element_blank(), panel.border = element_rect(colour = "black", fill=NA, size=.5))


summary(vel_ptch_mdl <- glm(occurrence ~ vel_m_s, data = velocity, family = "binomial"))
confint(vel_ptch_mdl)
save(vel_ptch_mdl, file = "vel_ptch_mdl.rda")


unique(velocity$source[!is.na(velocity$occurrence)])

```

plots for depth

```{r}

load("typha_depth.RData")


#patch occurrence
ggplot(data = depth, mapping = aes(x = depth_cm, y = occurrence))+
  geom_point(alpha = 0.2, size = 3)+
  labs(x = "Depth (cm)", y = "Occurrence")+
  geom_smooth(method = "lm", formula = y ~ x + I(x^2))+
  theme(text = element_text(size=20), panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
        panel.background = element_blank(), panel.border = element_rect(colour = "black", fill=NA, size=.5))





summary(dep_ptch_mdl <- lm(occurrence ~ depth_cm + I(depth_cm^2), data = depth))
save(dep_ptch_mdl, file = "dep_ptch_mdl.rda")



#germination percent
ggplot(data = depth[!is.na(depth$germination_perc),], mapping = aes(x = depth_cm, y = germination_perc, color = species))+
  geom_point()+
  labs(x = "Depth (cm)", y = "Germination (%)")+
  geom_smooth(method = "lm", formula = y ~ x + I(x^2))+
  theme(text = element_text(size=20), panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
        panel.background = element_blank(), panel.border = element_rect(colour = "black", fill=NA, size=.5))

ggplot(data = depth[!is.na(depth$germination_perc),], mapping = aes(x = depth_cm, y = germination_perc))+
  geom_point()+
  labs(x = "Depth (cm)", y = "Germination (%)")+
  geom_smooth(method = "lm", formula = y ~ x + I(x^2))+
  theme(text = element_text(size=20), panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
        panel.background = element_blank(), panel.border = element_rect(colour = "black", fill=NA, size=.5))




summary(dep_germ_mdl <- lm(germination_perc~depth_cm + I(depth_cm^2) + species, data = depth))
save(dep_germ_mdl, file = "dep_germ_mdl.rda")




family = #seedling survial
ggplot(data = depth[!is.na(depth$seedling_survial_perc),], mapping = aes(x = depth_cm, y = seedling_survial_perc, color = species))+
  geom_point()+
  labs(x = "Depth (cm)", y = "Seedling survival (%)")+
  geom_smooth(method = "lm", formula = y ~ x + I(x^2))+
  theme(text = element_text(size=20), panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
        panel.background = element_blank(), panel.border = element_rect(colour = "black", fill=NA, size=.5))

ggplot(data = depth[!is.na(depth$seedling_survial_perc),], mapping = aes(x = depth_cm, y = seedling_survial_perc))+
  geom_point()+
  labs(x = "Depth (cm)", y = "Seedling survival (%)")+
  geom_smooth(method = "lm", formula = y ~ x + I(x^2))+
  theme(text = element_text(size=20), panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
        panel.background = element_blank(), panel.border = element_rect(colour = "black", fill=NA, size=.5))



summary(dep_sdlng_mdl <- lm(seedling_survial_perc~depth_cm + I(depth_cm^2) + species, data = depth))
save(dep_sdlng_mdl, file = "dep_sdlng_mdl.rda")



unique(depth$source[!is.na(depth$occurrence)])
unique(depth$source[!is.na(depth$germination_perc)])
unique(depth$source[!is.na(depth$seedling_survial_perc)])

```

Plots for temperature

```{r}

load("typha_temp.RData")

ggplot(data = temp, aes(x = temp_midRng_c, y = germination_perc))+
  geom_jitter(alpha = 0.2, size = 3)+
  geom_smooth(method = "lm", formula = y ~ x + I(x^2))+
  theme(text = element_text(size=20), panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
        panel.background = element_blank(), panel.border = element_rect(colour = "black", fill=NA, size=.5))+
  labs(x = "Temperature Mid-Range (C)", y = "Germination (%)")


ggplot(data = temp, aes(x = high_temperature_c, y = germination_perc))+
  geom_jitter(alpha = 0.2, size = 3)+
  geom_smooth(method = "lm", formula = y ~ x + I(x^2))+
  theme(text = element_text(size=20), panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
        panel.background = element_blank(), panel.border = element_rect(colour = "black", fill=NA, size=.5))+
  labs(x = "High Temperature (C)", y = "Germination (%)")

summary(tmp_germ_mdl <- (lm(germination_perc ~ temperature_range_c + high_temperature_c + I(high_temperature_c^2), data = temp)))
save(tmp_germ_mdl, file = "tmp_germ_mdl.rda")


ggplot(data = temp, aes(x = temperature_range_c, y = germination_perc))+
  geom_jitter(alpha = 0.2, size = 3)+
  geom_smooth(method = "lm", formula = y ~ x + I(x^2))+
  theme(text = element_text(size=20), panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
        panel.background = element_blank(), panel.border = element_rect(colour = "black", fill=NA, size=.5))+
  labs(x = "Temperature Range (C)", y = "Germination (%)")

unique(temp$source[!is.na(temp$germination_perc)])



```